name: Pre-Code Review

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout order-management repo
        uses: actions/checkout@v3

      - name: Checkout wms-main repo
        uses: actions/checkout@v3
        with:
          repository: kityk-cargo/wms-main
          path: ./wms-main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run integration tests
        run: ./gradlew integrationTest
        env:
          SPRING_PROFILES_ACTIVE: test
          TESTCONTAINERS_RYUK_DISABLED: "true"

  openapi-validation:
    name: OpenAPI Schema Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run application to generate OpenAPI schema
        run: |
          ./gradlew bootRun &
          sleep 30
          curl -s http://localhost:8080/docs > openapi.json

      - name: Validate OpenAPI Schema
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi.json 