name: Release Pipeline

on:
  workflow_dispatch:  # manual trigger
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set build version tag
        id: tag
        run: |
          MAJOR=0
          MINOR=1
          BUILD=$(date +'%Y%m%d-%H%M')
          VERSION="${MAJOR}.${MINOR}.${BUILD}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          git tag ${VERSION}
          git push origin ${VERSION}

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Generate OpenAPI specs
        run: |
          ./gradlew generateOpenApiDocs
          # Convert JSON to YAML
          npm install -g json2yaml
          json2yaml build/api-docs/openapi.json > openapi.yaml

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/wms-order-management:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/wms-order-management:latest

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            build/libs/*.jar
            openapi.json
            openapi.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}